# Generated by Django 4.2.5 on 2023-09-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0003_alter_appuser_picture_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='picture_path',
            field=models.ImageField(blank=True, height_field='200', null=True, upload_to='profile_pics/', width_field='200'),
        ),
    ]
